---
apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: 172.17.255.10
spec:
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: 172.17.255.10
spec:
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10