image:
  tag: v0.1.3
  pullPolicy: IfNotPresent
  repository: gcr.io/google-samples/microservices-demo/frontend

replicas: 1

service:
  type: NodePort
  port: 80
  targetPort: 8080
  NodePort: 30001

ingress:
  host: shop.158.160.135.186.nip.io
  port: 80