env:
  GF_AUTH_DISABLE_LOGIN_FORM: true
  GF_AUTH_ANONYMOUS_ENABLED: true
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      editable: false
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    nginx-demo:
      gnetId: '12708'
      datasource: 'prometheus'

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prometheus
      id: prometheus
      type: prometheus
      url: http://prometheus-operated:9090
      access: proxy
      isDefault: true