---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: viewer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: viewer
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:prometheus
    namespace: prometheus
roleRef:
    kind: ClusterRole
    name: viewer
    apiGroup: rbac.authorization.k8s.io