apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: straymoonfox/paymentservice:v0.0.2
        resources: {}
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0%
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
---