apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-metrics
    labels:
      app: nginx-metrics 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-metrics
  template:
    metadata:
      labels:
        app: nginx-metrics
    spec:
      containers:
      - name: nginx-metrics
        image: straymoonfox/nginx-metrics:latest
        ports:
        - containerPort: 80
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter
        args:
          - '-nginx.scrape-uri=http://127.0.0.1:8080/basic_status'
        ports:
        - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics
  labels:
    app: nginx-metrics
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: nginx-prometheus-exporter
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: nginx-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-metrics-service-monitor
  namespace: default
  labels:
    release: prometheus-operator
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: nginx-metrics
  endpoints:
    - port: nginx-prometheus-exporter
      path: '/metrics'